server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: john
    password: 1767
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
logging:
  file:
    path: /tmp/testmybatisdynamic
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-sql-provider-type: org.mybatis.dynamic.sql.util.SqlProviderAdapter
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true